language: java
install:
- mvn clean package -B
- mvn test
before_script:
- ls
- ls ~/.ssh/
- git remote add origin-ssh git@github.com:k801030/visonliii-webapp.git
- git push origin-ssh master
script:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker build -t visonliii/webapp .
- docker push visonliii/webapp
- docker pull visonliii/webapp
- docker run -d -p 8080:8080 visonliii/webapp
env:
  global:
  - secure: nWxmsdgoGOgVA+Y8Q7XOUUQEDayI01BN04qKro4NpHl6V36eojyt2/fm5bFSA2y4ebqNr516jhfxCw/dBuPaSXN29j0FRDZxxRCyHDXWvv8quHXBxAq8qR9ArE9TEINkQ5QmjV2by+EBWNwdo+5JppaOniDAxO7MX7VcstfjgMbBNndFHhxsdh2+7ALA54gahMt6doRRIKWBNhJvja1GeiNe/eewXXOjy1vo0ayHf1c6RMvMjwpwSOsXRc3MlTYuzw55Utbq6ylH1ftJEwdJLf3sYK/ku+4v0P/tMF1oJfvyYEOuk3OlqOKl46NL61UcZs88YdMMC8iT2t2SwUkRetalrUrIsV5HNReIwgAON9GUnd/S1VHOl+H5NUTt5AsAXMmodIhOJbVsPcRkwC5gllbntuJyxcBBXHbceNiA5WUhhsEynqLMv2poctYt2eDjipLZ/aUwXqTP7oPkOOqWOhtAbZjkznGbFgI3F5fOV1nOieWmAhok2qfUB4YEy9YeINxycznHh6ePeS9gdVmpjZoPbgPSDB9T5/HOknhZkvcd4UahtLzNfu1MGECKsGpr3Hb9TI4juLWQZe0oiQesJyP24x1AXICoRywDbSsjFMtsaVejwNDxlkGXAmc6pFxuV3abTdkrBYmV+qh0OCZl2pcaaNLxCbNUXjC80/389ko=
  - secure: AQdX29V+z1kbX75uotgjK0hwT8+zjUHkCO/2Ct5Zx+/WruVTiC5X9A7irJ9ZI4m++wUmx1vOH3mX63s3lrsHYLkYjltRHAzk/H9oqv5XHYQj5w2RUZaJqGgKkAsN2WPI3bVBM0gjRtlS8qL7RXH8H0LT7EwOBMqY9+lNbwkf7IZBZ9/20Krs9BXoMi8VhY3ds66STiY2AnWI/BCWl7uOmHHIBcG+49jhqltBE1z49mtWs7hnYcnkAlCRNBtjKNO5D4vExR/ihn+VjkclaOdfSEBOw4BTiTgBzB4xwjmie1QKafAfIBK454hfZhNikKqhfL7XBBxXF7QEDD8aeV+c2E7Mnr0qoECPsax7yJ5P2aOY469sytLUS9sgGEPhYvXfAZ3aVplOGZfXrz0dCXnxCj5VnodHd1+9Uv6qLgmMRFdasfj0m2Qg2yENGaPjWXdcOrKEj0Dyk5aPk62rD+0Cd5pXOwcm7oDrvK6MVzizuhl1UiUT4/L5p4lDulI7M9UTyh7WvrOspAQ3wth7vxdAJloSL1aLtdzrrjrOK83eNs/wxT+iQZa/jUILUyxXdMMQnemertY5QgAo0WRvBKRAnC9AV4VFQWDhcbxoeUVyTTMLD10g18bwKvEPmnZaDyDWdoboEr2pC+twFJr2huFuo/2wWL0XrUpiSWgczHHmFZ4=
  - secure: jT6m2+G244ioZ9I852oDF/4qhcQrQzIiwheYy0PahvkzNKz4oBq+3TKS8W7pZS2QYDb+f5lEFHOuNAsRClk1Lx6bBUY5l5tP+fQ3KREBLTMWV3ynOja//B17amu3dLn/S3Kfk6zwOxlbMQqn33pFT66hCh/r+XoNJ+xwFvUVQEIAHok02TdUM+noq7PRliVn4fiz8+OjSAy52Sp0tZIk9HUYZxQ26ipfJqWH1ha9aGhDKM/ie3ePTH4Hxl25p7FFHxznUCGHUFuwXKLiGF0lHwG8hrBwNttxZ/mBZDHl/Eb9xlHLIZJ+fnsU/yYW5NGU5jA93w0+oozYYs43n4n9XrFVco1pElLB80+cYS4MUThXY4d1qirXP/yhhLFsoyWpfqn84qUBSlmBoETdwXeOiqjD0roPouf9LUloqsWwiyDQOuwXNGCCToCBWBZGcKLb/i1Zl4yLbegnt3RVcbmo/arCXdVa7qt+CpgF4fwkvZu+HfegM/tijhL3Rud3rhwTLYlQDx0X2k2p9b8rqXgEUSQNtQObfe24M2MobaRwfove4//F/k9G0HdLD3AW0pQNPC5Y7fiBXkjEzxBDnLZSpx/UjfkpU9/BTjCWGoPDqe75nuXT61yfroJtzOctuTWVsXfcxoukR49NsbrEe0Wpa9rNsLXURsqWOkM2ckEIKKI=
before_install:
- openssl aes-256-cbc -K $encrypted_9b8cf58c31ab_key -iv $encrypted_9b8cf58c31ab_iv
  -in github_travis_key.enc -out github_travis_key -d
